"""Generate dnsmasq.conf from current settings (proxyDHCP or full DHCP)."""
from sqlalchemy.orm import Session

from .. import config
from ..store import all_settings

HEADER = """# GENERATED by the PXE web app. Do not edit by hand.
port=0
log-dhcp
# Log DHCP/PXE activity to a file on the shared volume so the web app can show
# recent clients on the dashboard (works in proxyDHCP, which has no lease file).
log-facility=/dnsmasq/dnsmasq.log
"""

ARCH_DETECT = """
# --- Architecture detection (BIOS vs UEFI) ---
dhcp-match=set:efi32,option:client-arch,6
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efibc,option:client-arch,9

# iPXE identifies itself (so we serve the binary to raw firmware, but the HTTP
# menu to iPXE) via user-class and the encapsulated iPXE option (175).
dhcp-userclass=set:ipxe,iPXE
dhcp-match=set:ipxe,175
"""


def _boot_block(server_ip: str, tftp_enabled: bool) -> str:
    """Firmware -> iPXE handoff.

    Uses pxe-service (not dhcp-boot) for the binary handoff because that is the
    mechanism dnsmasq honours in proxyDHCP mode: raw firmware is chainloaded the
    arch-correct iPXE binary, while iPXE itself is sent the HTTP menu.
    """
    menu_host = server_ip or "127.0.0.1"
    lines = []
    if tftp_enabled:
        lines += [
            "enable-tftp",
            "tftp-root=/tftp",
            "",
            "# Raw firmware (not yet iPXE): chainload the matching iPXE binary.",
            "pxe-prompt=\"Loading iPXE...\",1",
            "pxe-service=tag:!ipxe,x86PC,\"iPXE (BIOS)\",undionly.kpxe",
            "pxe-service=tag:!ipxe,X86-64_EFI,\"iPXE (UEFI)\",ipxe.efi",
            "pxe-service=tag:!ipxe,BC_EFI,\"iPXE (UEFI)\",ipxe.efi",
            "",
        ]
    # Once iPXE is running, chain it to the single HTTP menu.
    lines.append("# iPXE clients: load the HTTP boot menu.")
    lines.append(f"dhcp-boot=tag:ipxe,http://{menu_host}/boot.ipxe")
    return "\n".join(lines)


def build_config(settings: dict) -> str:
    server_ip = settings.get("server_ip", "")
    iface = settings.get("boot_interface", "eth0")
    dhcp_on = settings.get("svc_dhcp", "1") == "1"
    tftp_on = settings.get("svc_tftp", "1") == "1"
    mode = settings.get("dhcp_mode", "proxy")

    parts = [HEADER]
    if iface:
        parts.append(f"interface={iface}")
        # Bind ONLY the chosen interface so DHCP never leaks onto other NICs
        # (e.g. a production LAN that already has a DHCP server).
        parts.append("bind-interfaces")
        parts.append("except-interface=lo")
    parts.append(ARCH_DETECT)

    if dhcp_on:
        if mode == "full":
            parts.append(
                "# --- Full DHCP: this server assigns IP addresses ---\n"
                f"dhcp-range={settings.get('dhcp_range_start')},"
                f"{settings.get('dhcp_range_end')},"
                f"{settings.get('dhcp_subnet_mask')},12h\n"
                f"dhcp-option=option:router,{settings.get('dhcp_gateway')}\n"
                f"dhcp-option=option:dns-server,{settings.get('dhcp_dns')}"
            )
        else:
            # proxyDHCP: answer only PXE, leave addressing to the existing server.
            net = server_ip or "0.0.0.0"
            parts.append(
                "# --- proxyDHCP: runs beside your existing DHCP server ---\n"
                f"dhcp-range={net},proxy"
            )
        parts.append(_boot_block(server_ip, tftp_on))
    else:
        parts.append("# DHCP service disabled in Server Settings.")

    return "\n".join(parts) + "\n"


def render(db: Session) -> str:
    settings = all_settings(db)
    text = build_config(settings)
    out = config.DNSMASQ_DIR / "dnsmasq.conf"
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    return text
