"""Generate the single boot.ipxe menu served to both BIOS and UEFI clients.

The menu uses iPXE's default plain black-and-white text rendering — no colour
scheme or background is applied.  The iPXE binaries are built without
CONSOLE_FRAMEBUFFER (see dnsmasq/Dockerfile) so the menu runs in plain VGA text
mode, where the arrow keys decode correctly for navigating the choices.
"""
import logging

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from .. import config
from ..models import Image
from ..store import all_settings

log = logging.getLogger("beacon.ipxe")


def _header(server_ip: str, title: str) -> str:
    host = server_ip or "${next-server}"
    host_url = f"http://{host}"
    return f"""#!ipxe
# GENERATED by the PXE web app. Do not edit by hand.

set boot-url {host_url}
# Used by NFS-netboot images: kernel cmdline references ${{server-ip}} for nfsroot.
set server-ip {host}
set menu-title {title}
"""


MENU_TOP = """
:start
menu ${menu-title}
item --gap -- ----------------------- Operating Systems -----------------------
"""

MENU_FOOTER = """item --gap -- ----------------------------------------------------------------
item shell        iPXE shell
item reboot       Reboot
item exit_ipxe    Continue local boot
choose --default {default} --timeout 30000 target && goto ${target}

:shell
echo Type 'exit' to return to the menu.
shell
goto start

:reboot
reboot

:exit_ipxe
exit
"""


def _xcpng_label(tag: str, img: Image, base_url: str, args: str) -> str:
    """Chainload the per-image standalone GRUB, which multiboots Xen.

    iPXE cannot multiboot under UEFI (IMAGE_MULTIBOOT is BIOS-only), which is the
    arch most XCP-NG hosts boot. So we hand off to a grub.efi built at extraction
    time (services.images._build_xcpng_grub); GRUB fetches xen/vmlinuz/install.img
    over HTTP and does the multiboot2 itself.
    """
    # bootx64.efi sits in the same extracted dir as vmlinuz (os/<id>/).
    img_dir = img.initrd_path.rsplit("/", 1)[0]
    grub = f"{base_url}/{img_dir}/bootx64.efi"
    return (
        f":{tag}\n"
        f"echo Booting {img.name} (XCP-NG via GRUB) ...\n"
        f"chain {grub} || goto start\n"
    )


def _image_entries(images: list[Image]) -> tuple[str, str]:
    """Return (menu items, boot labels) for ready, enabled images."""
    items = []
    labels = []
    for img in images:
        tag = f"os_{img.id}"
        items.append(f"item {tag}        {img.name}")
        base_url = "${boot-url}"
        args = img.boot_args or ""
        if img.os_family == "xcpng":
            labels.append(_xcpng_label(tag, img, base_url, args))
            continue
        kernel = f"{base_url}/{img.kernel_path}"
        initrd = f"{base_url}/{img.initrd_path}"
        labels.append(
            f":{tag}\n"
            f"echo Booting {img.name} ...\n"
            f"kernel {kernel} {args} || goto start\n"
            f"initrd {initrd} || goto start\n"
            f"boot || goto start\n"
        )
    return "\n".join(items), "\n".join(labels)


def render(db: Session) -> str:
    settings = all_settings(db)
    server_ip = settings.get("server_ip", "")
    title = settings.get("menu_title", "Beacon")

    images = db.execute(
        select(Image).where(Image.status == "ready", Image.enabled == 1)
        # Case-insensitive so an uppercase name sorts among the lowercase ones
        # instead of ahead of them (SQLite's default order is case-sensitive).
        .order_by(func.lower(Image.name))
    ).scalars().all()

    items, labels = _image_entries(images)
    if not items:
        items = "item --gap -- (no images uploaded yet — add one in the web UI)"

    default = f"os_{images[0].id}" if images else "exit_ipxe"

    text = (
        _header(server_ip, title)
        + MENU_TOP
        + items + "\n"
        + MENU_FOOTER.replace("{default}", default)
        + "\n"
        + labels
    )

    out = config.BOOTROOT_DIR / "boot.ipxe"
    out.write_text(text)

    return text
