"""Generate the single boot.ipxe menu served to both BIOS and UEFI clients.

Modern look: a colour scheme (always supported) plus an optional background PNG
(best-effort; the menu still works if the iPXE build lacks PNG/console support).
"""
from sqlalchemy import select
from sqlalchemy.orm import Session

from .. import config
from ..models import Image
from ..store import all_settings


def _header(server_ip: str, title: str) -> str:
    host = server_ip or "${next-server}"
    host_url = f"http://{host}"
    # Every styling line is guarded with `|| goto styled` so that on any iPXE
    # build lacking a feature (PNG console, colour cmds) the script still falls
    # through to the menu instead of aborting.
    return f"""#!ipxe
# GENERATED by the PXE web app. Do not edit by hand.

set boot-url {host_url}
# Used by NFS-netboot images: kernel cmdline references ${{server-ip}} for nfsroot.
set server-ip {host}
set menu-title {title}

# --- Modern look: background image + colour scheme (all best-effort) -------
console --picture {host_url}/background.png --left 60 --right 30 --top 40 --bottom 60 || goto styled
colour --rgb 0x1a1d29 0 || goto styled
colour --rgb 0x00d2ff 4 || goto styled
cpair --foreground 7 --background 4 1 || goto styled
cpair --foreground 6 --background 0 0 || goto styled
:styled
"""


MENU_TOP = """
:start
menu ${menu-title}
item --gap -- ----------------------- Operating Systems -----------------------
"""

MENU_FOOTER = """item --gap -- ----------------------------------------------------------------
item shell        iPXE shell
item reboot       Reboot
item exit_ipxe    Continue local boot
choose --default {default} --timeout 30000 target && goto ${target}

:shell
echo Type 'exit' to return to the menu.
shell
goto start

:reboot
reboot

:exit_ipxe
exit
"""


def _image_entries(images: list[Image]) -> tuple[str, str]:
    """Return (menu items, boot labels) for ready, enabled images."""
    items = []
    labels = []
    for img in images:
        tag = f"os_{img.id}"
        items.append(f"item {tag}        {img.name}")
        kernel = f"${{boot-url}}/{img.kernel_path}"
        initrd = f"${{boot-url}}/{img.initrd_path}"
        args = img.boot_args or ""
        labels.append(
            f":{tag}\n"
            f"echo Booting {img.name} ...\n"
            f"kernel {kernel} {args}\n"
            f"initrd {initrd}\n"
            f"boot || goto start\n"
        )
    return "\n".join(items), "\n".join(labels)


def render(db: Session) -> str:
    settings = all_settings(db)
    server_ip = settings.get("server_ip", "")
    title = settings.get("menu_title", "Beacon")

    images = db.execute(
        select(Image).where(Image.status == "ready", Image.enabled == 1)
        .order_by(Image.name)
    ).scalars().all()

    items, labels = _image_entries(images)
    if not items:
        items = "item --gap -- (no images uploaded yet — add one in the web UI)"

    default = f"os_{images[0].id}" if images else "exit_ipxe"

    text = (
        _header(server_ip, title)
        + MENU_TOP
        + items + "\n"
        + MENU_FOOTER.replace("{default}", default)
        + "\n"
        + labels
    )

    out = config.BOOTROOT_DIR / "boot.ipxe"
    out.write_text(text)
    return text
